site_name: H5P Go SDK Documentation
site_description: A Go library for creating, manipulating, and validating H5P (HTML5 Package) content
site_author: Grokify
site_url: https://grokify.github.io/h5p-go/

repo_name: grokify/h5p-go
repo_url: https://github.com/grokify/h5p-go

docs_dir: docsrc
site_dir: docs

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Concepts: getting-started/concepts.md
  - User Guide:
    - Question Sets: guide/question-sets.md
    - Typed Questions: guide/typed-questions.md
    - H5P Packages: guide/h5p-packages.md
    - Validation: guide/validation.md
  - API Reference:
    - Core Types: api/core-types.md
    - Builder Pattern: api/builder.md
    - Schemas: api/schemas.md
    - Semantics: api/semantics.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Usage: examples/advanced.md
    - Package Creation: examples/packages.md
  - Reference:
    - H5P Specification: reference/h5p-spec.md
    - File Structure: reference/file-structure.md
    - Standards Compliance: reference/standards.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Roadmap: development/roadmap.md

plugins:
  - search